# Generated by Django 5.2.4 on 2025-08-02 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('admin', 'administrateur'), ('partenaire', 'partenaire'), ('candidat', 'candidat')], max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('nom_du_centre', models.CharField(max_length=150)),
                ('numero_telephone', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('nationnalite', models.CharField(max_length=150)),
                ('profession', models.CharField(max_length=150)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('telephone', models.IntegerField()),
                ('photo_portrait', models.ImageField(help_text="L'image doit être clair, de préférence avec fond blanc", upload_to='photo/portrait/')),
                ('piece_identite', models.ImageField(help_text='La piece fdoit être à jour et les informations doivent être lisibles', upload_to='photo/piecesidentite/')),
                ('confirmation', models.ImageField(upload_to='photo/confirmation/')),
                ('ville_residence', models.CharField(max_length=150)),
                ('langue_usuelle', models.CharField(max_length=150)),
                ('favoris', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('EA', 'En Attente'), ('A', 'Approuvé'), ('V', 'Validé'), ('NV', 'Non validé')], default='EA', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ourAPP.partenaire', verbose_name='related partenaire')),
            ],
        ),
    ]
