# Generated by Django 5.2.4 on 2025-08-02 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=1000)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourAPP.partenaire')),
            ],
        ),
    ]
