# Generated by Django 5.2.4 on 2025-08-02 03:36

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourAPP', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='libelle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='numero_telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
