# Generated by Django 5.2.4 on 2025-08-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourAPP', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partenaire',
            name='email',
        ),
    ]
