# Generated by Django 5.2.4 on 2025-08-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourAPP', '0003_alter_candidat_telephone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='piece_identite',
            new_name='piece_identite_recto',
        ),
        migrations.AddField(
            model_name='candidat',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='piece_identite_verso',
            field=models.ImageField(default=None, help_text='La piece fdoit être à jour et les informations doivent être lisibles', upload_to='photo/piecesidentite/'),
        ),
    ]
