# Generated by Django 5.2.4 on 2025-08-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourAPP', '0003_remove_partenaire_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='telephone',
            new_name='numero_telephone',
        ),
    ]
