# Generated by Django 5.2.4 on 2025-08-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourAPP', '0004_rename_telephone_candidat_numero_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='confirmation',
            field=models.ImageField(blank=True, null=True, upload_to='media/confirmation/'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='favoris',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nationnalite',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='photo_portrait',
            field=models.ImageField(help_text="L'image doit être clair, de préférence avec fond blanc", max_length=300, upload_to='media/portrait/'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='piece_identite_recto',
            field=models.ImageField(help_text='La piece fdoit être à jour et les informations doivent être lisibles', max_length=300, upload_to='media/piecesidentite/'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='piece_identite_verso',
            field=models.ImageField(default=None, help_text='La piece fdoit être à jour et les informations doivent être lisibles', max_length=300, upload_to='media/piecesidentite/'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
