# Generated by Django 5.2.4 on 2025-08-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourAPP', '0005_alter_candidat_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='statut',
            field=models.CharField(choices=[('En Attente', 'En Attente'), ('Approuvé', 'Approuvé'), ('Validé', 'Validé'), ('Non Validé', 'Non Validé')], default='en Attente', max_length=20),
        ),
    ]
